from flask import Flask

app = Flask(__name__)

html_lines = []

def add(line):
    html_lines.append(line)

add("<!DOCTYPE html>")
add("<html lang='ar' dir='rtl' x-data=\"{ darkMode: localStorage.getItem('darkMode') === 'true' }\" x-init=\"$watch('darkMode', val => localStorage.setItem('darkMode', val))\" :class=\"{ 'dark': darkMode }\">")
add("<head>")
add("<meta charset='UTF-8'>")
add("<meta name='viewport' content='width=device-width, initial-scale=1.0'>")
add("<title>ركن السعادة للتجارة | فرع الشحر</title>")
add("<script src='https://cdn.tailwindcss.com'></script>")
add("<script>")
add("tailwind.config = { darkMode: 'class', theme: { extend: { colors: { brand: { pink: '#ec4899', dark: '#0b070d' } } } } }")
add("</script>")
add("<script defer src='https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js'></script>")
add("<link href='https://fonts.googleapis.com/css2?family=Tajawal:wght@300;400;700;900&display=swap' rel='stylesheet'>")
add("<style>")
add("body { font-family: 'Tajawal', sans-serif; transition: background-color 0.5s ease, color 0.5s ease; }")
add(".glass-card { background: rgba(255,255,255,0.75); backdrop-filter: blur(14px); border: 1px solid rgba(236,72,153,0.2); transition: all 0.3s ease; }")
add(".dark .glass-card { background: rgba(11,7,13,0.75); border: 1px solid rgba(236,72,153,0.15); }")
add(".pink-glow { text-shadow: 0 0 20px rgba(236,72,153,0.6); }")
add(".dark .pink-glow { text-shadow: 0 0 25px rgba(236,72,153,0.8); }")
add("::-webkit-scrollbar { width: 8px; }")
add("::-webkit-scrollbar-thumb { background: #ec4899; border-radius: 4px; }")
add("@keyframes fadeInUp { from { opacity: 0; transform: translateY(30px); } to { opacity: 1; transform: translateY(0); } }")
add(".animate-fade-up { animation: fadeInUp 0.8s ease-out forwards; }")
add("@keyframes float { 0%,100% { transform: translateY(0); } 50% { transform: translateY(-15px); } }")
add(".animate-float { animation: float 6s ease-in-out infinite; }")
add("@keyframes pulseSlow { 0%,100% { opacity: 0.4; } 50% { opacity: 0.7; } }")
add(".animate-pulse-slow { animation: pulseSlow 4s cubic-bezier(0.4,0,0.6,1) infinite; }")
add("</style>")
add("</head>")
add("<body class='bg-gray-50 text-gray-900 dark:bg-brand-dark dark:text-white overflow-x-hidden'>")

add("<nav class='fixed top-0 w-full z-50 glass-card border-b border-pink-200 dark:border-pink-900/30 px-6 py-4 flex justify-between items-center shadow-sm'>")
add("<div class='flex items-center gap-3'>")
add("<div class='w-10 h-10 rounded-full bg-gradient-to-tr from-brand-pink to-rose-400 flex items-center justify-center font-black text-xl text-white shadow-lg'>س</div>")
add("<div>")
add("<span class='text-xl font-black block leading-none'>ركن <span class='text-brand-pink'>السعادة</span></span>")
add("<span class='text-[10px] text-gray-500 dark:text-pink-300 font-light tracking-widest'>للتجارة - فرع الشحر</span>")
add("</div>")
add("</div>")
add("<div class='hidden md:flex gap-6 font-medium text-sm'>")
add("<a href='#hero' class='hover:text-brand-pink transition-colors'>الرئيسية</a>")
add("<a href='#about' class='hover:text-brand-pink transition-colors'>من نحن</a>")
add("<a href='#products' class='hover:text-brand-pink transition-colors'>الأقسام</a>")
add("<a href='#features' class='hover:text-brand-pink transition-colors'>لماذا نحن</a>")
add("<a href='#contact' class='hover:text-brand-pink transition-colors'>تواصل معنا</a>")
add("</div>")
add("<button @click='darkMode = !darkMode' class='p-2 rounded-full hover:bg-gray-200 dark:hover:bg-gray-800 transition-colors'>")
add("<svg x-show='!darkMode' class='w-5 h-5 text-gray-600' fill='none' stroke='currentColor' viewBox='0 0 24 24'><path stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z'></path></svg>")
add("<svg x-show='darkMode' class='w-5 h-5 text-yellow-400' fill='none' stroke='currentColor' viewBox='0 0 24 24'><path stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z'></path></svg>")
add("</button>")
add("</nav>")

add("<section id='hero' class='relative min-h-screen flex items-center justify-center pt-24 px-6 text-center overflow-hidden'>")
add("<div class='absolute top-1/4 right-1/4 w-96 h-96 bg-brand-pink/20 rounded-full blur-3xl pointer-events-none animate-pulse-slow'></div>")
add("<div class='absolute bottom-1/4 left-1/4 w-96 h-96 bg-rose-500/15 rounded-full blur-3xl pointer-events-none animate-pulse-slow'></div>")
add("<div class='max-w-4xl z-10 animate-fade-up'>")
add("<span class='inline-block px-4 py-1.5 rounded-full glass-card text-brand-pink font-semibold text-xs mb-6 border border-pink-500/30'>🛍️ أحدث تشكيلات الموضة والسجاد والمنسوجات في الشحر</span>")
add("<h1 class='text-4xl md:text-6xl font-black mb-6 leading-tight'>عالم الأناقة والجمال في <br><span class='text-transparent bg-clip-text bg-gradient-to-r from-brand-pink via-rose-400 to-amber-500 pink-glow'>ركن السعادة للتجارة</span></h1>")
add("<p class='text-gray-600 dark:text-gray-300 mb-8 max-w-2xl mx-auto font-light text-sm md:text-base'>نقدم لكم أرقى الفساتين والملابس الجاهزة، وأجود أنواع السجاد والمنسوجات الفاخرة بأسعار مميزة وجودة عالية.</p>")
add("<div class='flex flex-col sm:flex-row gap-4 justify-center'>")
add("<a href='#products' class='bg-brand-pink hover:bg-pink-600 text-white font-bold px-8 py-3.5 rounded-xl shadow-xl transition-all hover:scale-105'>تصفح الأقسام</a>")
add("<a href='https://wa.me/967780415415' target='_blank' class='glass-card hover:bg-gray-100 dark:hover:bg-white/10 font-bold px-8 py-3.5 rounded-xl transition-all hover:scale-105'>📲 الطلب عبر الواتساب</a>")
add("</div>")
add("</div>")
add("</section>")

add("<section id='about' class='py-20 px-6 max-w-7xl mx-auto'>")
add("<div class='grid grid-cols-1 md:grid-cols-2 gap-12 items-center'>")
add("<div class='animate-fade-up'>")
add("<span class='text-brand-pink font-bold text-sm mb-2 block'>✨ قصتنا</span>")
add("<h2 class='text-3xl md:text-4xl font-black mb-6'>من <span class='text-brand-pink'>نحن</span>؟</h2>")
add("<p class='text-gray-600 dark:text-gray-300 leading-relaxed mb-4 text-sm md:text-base'>منذ انطلاقتنا في مدينة <strong>الشحر</strong> بمحافظة حضرموت، وضعنا نصب أعيننا هدفاً واحداً: أن نكون الوجهة الأولى لكل من يبحث عن الأناقة والجودة. في <strong>ركن السعادة للتجارة</strong>، نؤمن أن التفاصيل الصغيرة هي ما تصنع الفرق الكبير.</p>")
add("<p class='text-gray-600 dark:text-gray-300 leading-relaxed mb-6 text-sm md:text-base'>نحن لا نبيع مجرد ملابس أو سجاد، بل نقدم تجربة تسوق متكاملة تجمع بين الأصالة والحداثة.</p>")
add("<div class='flex gap-6'>")
add("<div><span class='block text-3xl font-black text-brand-pink'>+10</span><span class='text-xs text-gray-500'>سنوات خبرة</span></div>")
add("<div><span class='block text-3xl font-black text-brand-pink'>+5000</span><span class='text-xs text-gray-500'>عميل سعيد</span></div>")
add("<div><span class='block text-3xl font-black text-brand-pink'>100%</span><span class='text-xs text-gray-500'>جودة مضمونة</span></div>")
add("</div>")
add("</div>")
add("<div class='relative animate-fade-up'>")
add("<img src='https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80' class='rounded-3xl shadow-2xl w-full h-96 object-cover border-4 border-white dark:border-gray-800'>")
add("<div class='absolute -bottom-6 -right-6 w-32 h-32 bg-brand-pink rounded-full flex items-center justify-center text-white font-black text-xl shadow-xl animate-float'>أصالة <br> وجودة</div>")
add("</div>")
add("</div>")
add("</section>")

add("<section id='products' class='py-16 px-6 max-w-7xl mx-auto bg-gray-100 dark:bg-white/5 rounded-3xl my-8'>")
add("<div class='text-center mb-12 animate-fade-up'>")
add("<h2 class='text-3xl font-black mb-2'>أقسام <span class='text-brand-pink'>المتجر</span></h2>")
add("<p class='text-gray-500 dark:text-gray-400 text-sm'>تصفح أقسامنا المتنوعة واختر ما يناسبك</p>")
add("</div>")
add("<div class='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6'>")

def card(img_url, category, title, desc):
    add("<div class='glass-card rounded-2xl overflow-hidden hover:border-brand-pink/50 transition-all duration-300 group animate-fade-up flex flex-row h-48'>")
    add("<div class='relative w-2/5 overflow-hidden'>")
    add("<img src='" + img_url + "' class='w-full h-full object-cover group-hover:scale-110 transition-transform duration-700'>")
    add("</div>")
    add("<div class='p-4 w-3/5 flex flex-col justify-center'>")
    add("<span class='text-brand-pink text-[10px] font-bold mb-1'>" + category + "</span>")
    add("<h3 class='text-base font-bold mb-1 group-hover:text-brand-pink transition-colors'>" + title + "</h3>")
    add("<p class='text-gray-500 dark:text-gray-400 text-[11px] mb-3 leading-relaxed'>" + desc + "</p>")
    add("<a href='https://wa.me/967780415415' target='_blank' class='bg-brand-pink hover:bg-pink-600 text-white font-bold px-3 py-1.5 rounded-lg text-[11px] transition-all text-center'>اطلب الآن</a>")
    add("</div>")
    add("</div>")

card("https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80", "ملابس نسائية", "فساتين وجلابيات", "أرقى تصاميم الفساتين بتطريز أنيق.")
card("https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=80", "عبايات", "عبايات وجلابيات", "تصاميم عصرية وخامات مريحة.")
card("https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=800&q=80", "ملابس أطفال", "ملابس الأطفال", "أزياء مريحة وعملية للأطفال.")
card("https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&w=800&q=80", "سجاد ومفارش", "السجاد الفاخر", "سجاد بجودة عالية ونقوش مميزة.")
card("https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=800&q=80", "مفارش وستائر", "مفارش السرير", "مجموعات متناسقة لتجديد منزلك.")
card("https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=800&q=80", "منسوجات", "الأقمشة والمنسوجات", "أجود أنواع الأقمشة والخامات.")
card("https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80", "عطور وبخور", "العطور والبخور", "روائح فاخرة تدوم طويلاً.")
card("https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80", "حقائب وأحذية", "الحقائب والأحذية", "تشكيلة أنيقة لتكتمل إطلالتك.")
card("https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?auto=format&fit=crop&w=800&q=80", "مستلزمات منزلية", "المستلزمات المنزلية", "كل ما يحتاجه منزلك بجودة عالية.")

add("</div>")
add("</section>")

add("<section id='features' class='py-20 px-6 max-w-7xl mx-auto'>")
add("<div class='text-center mb-12 animate-fade-up'>")
add("<h2 class='text-3xl font-black mb-2'>لماذا تختار <span class='text-brand-pink'>ركن السعادة</span>؟</h2>")
add("<p class='text-gray-500 dark:text-gray-400 text-sm'>نحن نتميز بما نقدمه لعملائنا الكرام</p>")
add("</div>")
add("<div class='grid grid-cols-1 md:grid-cols-4 gap-6'>")
add("<div class='glass-card p-6 rounded-2xl text-center hover:-translate-y-2 transition-transform duration-300 animate-fade-up'><div class='w-16 h-16 mx-auto bg-pink-100 dark:bg-pink-900/30 text-brand-pink rounded-full flex items-center justify-center text-2xl mb-4'>✨</div><h3 class='font-bold mb-2'>جودة عالية</h3><p class='text-xs text-gray-500 dark:text-gray-400'>نختار منتجاتنا بعناية من أفضل المصادر.</p></div>")
add("<div class='glass-card p-6 rounded-2xl text-center hover:-translate-y-2 transition-transform duration-300 animate-fade-up'><div class='w-16 h-16 mx-auto bg-pink-100 dark:bg-pink-900/30 text-brand-pink rounded-full flex items-center justify-center text-2xl mb-4'>💰</div><h3 class='font-bold mb-2'>أسعار منافسة</h3><p class='text-xs text-gray-500 dark:text-gray-400'>أفضل الأسعار مع عروض وخصومات.</p></div>")
add("<div class='glass-card p-6 rounded-2xl text-center hover:-translate-y-2 transition-transform duration-300 animate-fade-up'><div class='w-16 h-16 mx-auto bg-pink-100 dark:bg-pink-900/30 text-brand-pink rounded-full flex items-center justify-center text-2xl mb-4'>🚚</div><h3 class='font-bold mb-2'>توصيل سريع</h3><p class='text-xs text-gray-500 dark:text-gray-400'>خدمة توصيل سريعة وموثوقة.</p></div>")
add("<div class='glass-card p-6 rounded-2xl text-center hover:-translate-y-2 transition-transform duration-300 animate-fade-up'><div class='w-16 h-16 mx-auto bg-pink-100 dark:bg-pink-900/30 text-brand-pink rounded-full flex items-center justify-center text-2xl mb-4'>🤝</div><h3 class='font-bold mb-2'>خدمة ممتازة</h3><p class='text-xs text-gray-500 dark:text-gray-400'>فريقنا متواجد دائماً لمساعدتك.</p></div>")
add("</div>")
add("</section>")

add("<section id='contact' class='py-16 px-6 max-w-7xl mx-auto'>")
add("<div class='glass-card rounded-3xl p-8 md:p-12 animate-fade-up'>")
add("<div class='grid grid-cols-1 md:grid-cols-3 gap-8 text-center'>")
add("<div class='p-4'><div class='text-4xl mb-3'>📍</div><h4 class='font-bold text-lg mb-2'>الموقع</h4><p class='text-gray-500 dark:text-gray-400 text-sm'>حضرموت - الشحر</p></div>")
add("<div class='p-4 border-y md:border-y-0 md:border-x border-gray-200 dark:border-white/10'><div class='text-4xl mb-3'>📞</div><h4 class='font-bold text-lg mb-2'>للطلب</h4><a href='https://wa.me/967780415415' class='text-brand-pink font-bold text-lg hover:underline block'>780415415</a></div>")
add("<div class='p-4'><div class='text-4xl mb-3'>🌐</div><h4 class='font-bold text-lg mb-2'>تابعنا</h4><p class='text-gray-500 dark:text-gray-400 text-sm'>@rukn.als3adahl</p></div>")
add("</div>")
add("</div>")
add("</section>")

add("<footer class='py-8 text-center text-gray-500 text-xs border-t border-gray-200 dark:border-white/5 mt-8'>")
add("<p>© 2026 ركن السعادة للتجارة - فرع الشحر. جميع الحقوق محفوظة.</p>")
add("</footer>")
add("</body>")
add("</html>")

html_code = "\n".join(html_lines)

@app.route("/")
def home():
    return html_code

if __name__ == "__main__":
    print("\n" + "=" * 50)
    print("🚀 جاري تشغيل موقع (ركن السعادة للتجارة)...")
    print("👉 افتح المتصفح على: http://127.0.0.1:5000")
    print("=" * 50 + "\n")
    app.run(host="0.0.0.0", port=5000, debug=True)
